title: Без фильтров !
description: >-
  Современный VPN сервис с надежным уровнем защиты и анонимности

email: bfiltrov@gmail.com

aux_links:
  Войти в личный кабинет:
    - https://t.me/bez_filtrov_vpn_bot

domain: bez-filtrov.github.io
url: "https://bez-filtrov.github.io" 
baseurl: "/" 

remote_theme: https://github.com/just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
